spring:
    datasource:
#        url : jdbc:mysql://localhost:3306/What?characterEncoding=UTF-8&serverTimezone=UTC&autoReconnection=true
        url : jdbc:mysql://what.cncoahqwcoi4.us-east-2.rds.amazonaws.com:3306/What?characterEncoding=UTF-8&serverTimezone=UTC&autoReconnection=true
        username : admin
        password : dkdusaos-1
        driver-class-name : com.mysql.jdbc.Driver
        #        generate-unique-name: true
        hikari:
            schema : What
#    devtools:
#    livereload:
#    enabled: true
#    freemarker:
#    cache: false
#    mustache:
#    expose-session-attributes: true
    jpa:
        show-sql : true
#        hibernate:
#            dialect: org.hibernate.dialect.MySQL5Dialect
#            naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
#        database: mysql
#    servlet:
#    multipart:
#    max-file-size: 100MB
#    max-request-size: 100MB
#    http:
#    multipart:
#    enabled: false
#    mvc:
#    async:
#    request-timeout: 5000
jwt:
    secret : SEVZLVdIQVQtQVJFLVlPVS1UQUxLSU5HLUFCT1VULUFORC1GSUdIVElORy1UTy1HRVQtQS1KT0IK #HEY-WHAT-ARE-YOU-TALKING-ABOUT-AND-FIGHTING-TO-GET-A-JOB
    token-validity-in-seconds : 1800
    refresh-token-validity-in-seconds : 86400